( prog (
    (setq x 4)
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
            (setq lol 2))
    (cond (equal x 4)
            (setq lol 2))
    (cond (equal x 4)
            (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
        (setq lol 2))
    (cond (equal x 4)
            (setq lol 2))
    (cond (equal x 4)
            (setq lol 2))
    (cond (equal x 4)
            (setq lol 2))

  ( return x ) )
)