name: Testing
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Run tests
        run: gradle test -i
